service: first-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /users/hello
          method: get

  create:
    handler: handler.create
    events:
      - http:
          path: /users/create
          method: get
